@startuml

class Gameplay {}

class Grilla {
    + avanzar(vehiculo: Vehiculo, direccion: String)
}

class Usuario {}

abstract class Vehiculo {
    # posicion: int
    # movimientos: int
    + posicion(): int
    + mover(): void
    + {abstract} pasarPor(obstaculo: Obstaculo)
    + serPenalizadoCon(puntosPenalizacion: int)
}

class Moto {
    + pasarPor(obstaculo: Obstaculo)
}

class Auto {
    + pasarPor(obstaculo: Obstaculo)
}

class Auto4x4 {
    - contadorPozos: int
    + pasarPor(obstaculo: Obstaculo)
}

abstract class Obstaculo {
    # posicion: Posicion
    + {abstract} penalizar(vehiculo:Vehiculo)
    + tieneLaMismaPosicion(posicion:int)
}

class Pozo {
    + penalizar(vehiculo:Vehiculo)
}

class Piquete {
    + penalizar(vehiculo:Vehiculo)
}

Gameplay --> Grilla
Usuario --> Vehiculo

Gameplay --> "1..*" Usuario
Grilla ..> Vehiculo
Grilla *-- "0..*" Obstaculo
Vehiculo <|-- Moto
Vehiculo <|-- Auto
Vehiculo <|-- Auto4x4

Obstaculo <|-- Pozo
Obstaculo <|-- Piquete

@enduml
