@startuml

class Gameplay {}

class Grilla {
    + avanzar(vehiculo: Vehiculo, direccion: String)
}

class Usuario {}

abstract class Vehiculo {
    # posicionActual: int
    # movimientos: int
    + posicion(): int
    + actualizarPosicion(proximaPosicion: int)
    + actualizarCantidadMovimientos(movimientos: int)
}

class Moto {}

abstract class Obstaculo {
    # posicion: Posicion
    + {abstract} penalizar(posicion: int)
}

class Pozo {
    + penalizar(posicion: int)
}

class Piquete {
    + penalizar(posicion: int)
}

Gameplay --> Grilla
Usuario --> Vehiculo

Gameplay --> "1..*" Usuario
Grilla ..> Vehiculo
Grilla *-- "0..*" Obstaculo
Vehiculo <|-- Moto
Vehiculo <|-- Auto
Vehiculo <|-- Auto4x4

Obstaculo <|-- Pozo
Obstaculo <|-- Piquete

@enduml