@startuml

title Una moto atraviesa la ciudad, pasa por un pozo y tiene 3 Movimientos de penalizacion

actor Gameplay
participant ":Grilla" as Grilla
participant ":Obstaculos" as Obstaculos
participant ":Moto" as Moto

activate Gameplay
Gameplay -> Grilla: avanzar(unVehiculo: Moto)
Grilla -> Grilla: estaEnJuego(identificacionVehiculo: String)
Grilla -> Obstaculos: hayObstaculoAlFrente(unaUbicacion: ubicacionFinal)
return false
Grilla -> Moto: avanzar(unaCantidad: X)

@enduml
