@startuml

class Gameplay {}

class Grilla {
    + avanzar(vehiculo: Vehiculo, direccion: String)
}

class Usuario {}

abstract class Vehiculo {
    # posicion: int
    # movimientos: int
    + posicion(): int
    + mover(): void
    + {abstract} pasarPor(obstaculo: Penalizador)
    + serPenalizadoCon(puntosPenalizacion: int)
}

class Moto {
    + pasarPor(obstaculo: Penalizador)
}

class Auto {
    + pasarPor(obstaculo: Penalizador)
}

class Auto4x4 {
    - contadorPozos: int
    + pasarPor(obstaculo: Penalizador)
}

interface Penalizador {
    + {abstract} penalizar(vehiculo:Vehiculo)
    + {abstract} tieneLaMismaPosicion(posicion:int)
}

class Pozo {
    + penalizar(vehiculo:Vehiculo)
}

class Piquete {
    + penalizar(vehiculo:Vehiculo)
}

Gameplay --> Grilla
Usuario --> Vehiculo

Gameplay --> "1..*" Usuario
Grilla ..> Vehiculo
Grilla *-- "0..*" Penalizador
Vehiculo <|-- Moto
Vehiculo <|-- Auto
Vehiculo <|-- Auto4x4

Penalizador <|.. Pozo
Penalizador <|.. Piquete

@enduml
