@startuml

actor Gameplay
participant "grilla : Grilla" as Grilla
participant "sorpresa : SorpresaCambioVehiculo" as SorpresaCambioVehiculo
participant "pozo : Pozo" as Pozo
participant "auto4x4 : Auto4x4" as Auto4x4
participant "moto : Moto" as Moto
participant "auto: Vehiculo" as Vehiculo
participant "posicion : Posicion" as Posicion

activate Gameplay

Gameplay -> Grilla: avanzar(auto, 'd')
Grilla -> Vehiculo: getPosicionSiguiente('d')
Vehiculo --> Grilla: posicion

Grilla -> Vehiculo: abrirSorpresa(sorpresa)
Vehiculo -> SorpresaCambioVehiculo: activar(vehiculo)
SorpresaCambioVehiculo -> Vehiculo: cambiarTipo()
Vehiculo -> Auto4x4: cambiarTipo()
Vehiculo --> Auto4x4: moto

Gameplay -> Grilla: avanzar(auto, 'd')
Grilla -> Vehiculo: getPosicionSiguiente('d')
Vehiculo --> Grilla: posicion

Grilla -> Grilla: pasarPorObstaculos(vehiculo, 'd')
Grilla -> Auto4x4: pasarPor(pozo)
Auto4x4 -> Moto: pasarPor(pozo)
Moto -> Pozo: visit(moto)
Moto --> Pozo: 3
Pozo --> SorpresaCambioVehiculo: 3
SorpresaCambioVehiculo --> Vehiculo: 3

Gameplay -> Vehiculo: movimientos()
return 5

deactivate Gameplay

@enduml