@startuml

title Auto4x4 pasa por sorpresa cambio de vehiculo cambia a moto pasa por Pozo es penalizado
actor Gameplay
participant "grilla : Grilla" as Grilla
participant "sorpresa : SorpresaCambioVehiculo" as SorpresaCambioVehiculo
participant "auto: Vehiculo" as Vehiculo
participant "auto4x4 : Auto4x4" as Auto4x4
participant "moto : Moto" as Moto
participant "pozo : Pozo" as Pozo

activate Gameplay

Gameplay -> Grilla: avanzar(auto, 'd')
Grilla -> Vehiculo: getPosicionSiguiente('d')
Vehiculo --> Grilla: posicion

Grilla -> Vehiculo: abrirSorpresa(sorpresa)
Vehiculo -> SorpresaCambioVehiculo: activar(vehiculo)
SorpresaCambioVehiculo -> Vehiculo: cambiarTipo()
Vehiculo -> Auto4x4: cambiarTipo()
Auto4x4 -> Moto: new
Moto --> Auto4x4: moto
Auto4x4 --> Vehiculo: moto

Gameplay -> Grilla: avanzar(auto, 'd')
Grilla -> Vehiculo: getPosicionSiguiente('d')
Vehiculo --> Grilla: posicion

Grilla -> Grilla: pasarPorObstaculos(vehiculo, 'd')
Grilla -> Auto4x4: pasarPor(pozo)
Auto4x4 -> Moto: pasarPor(pozo)
Moto -> Pozo: visit(moto)
Pozo --> Moto: 3
Moto --> Vehiculo: 3

Gameplay -> Vehiculo: movimientos()
return 5

deactivate Gameplay

@enduml