@startuml
'https://plantuml.com/class-diagram

interface Vehiculo
{
+pasarPor(e:Piquete)
+pasarPor(e:Pozo)
+pasarPor(e:ControlPolicial)
}
class Auto
{
- Posicion posicion
+pasarPor(e:Piquete)
+pasarPor(e:Pozo)
+pasarPor(e:ControlPolicial)
}
class Moto
{
- Posicion posicion
+pasarPor(e:Piquete)
+pasarPor(e:Pozo)
+pasarPor(e:ControlPolicial)
}
class 4x4
{
- Posicion posicion
+pasarPor(e:Piquete)
+pasarPor(e:Pozo)
+pasarPor(e:ControlPolicial)
}
class Grilla
{
    -HashMap<Posicion, Obstaculo> obstaculos
    -int movimientos
    +getMovimientos()
    +avanzar(Vehiculo vehiculo,char direccion)
}

class Posicion
{
- int x
- int y
- List instances
+ transladar(Posicion nueva)
+   getPosicion(int x, int y)
+ siguiente(char direccion)
}
interface Obstaculo
{
    +penalizarA(v:Vehiculo)
}
class Piquete
{
+penalizarA(v:Vehiculo)
}
class ControlPolicial
{
+penalizarA(v:Vehiculo)
}
class Pozo
{

+penalizarA(v:Vehiculo) (v.visit(this)
}

Obstaculo <|.. Pozo
Obstaculo <|.. ControlPolicial
Obstaculo <|.. Piquete

Vehiculo <|.. Auto
Vehiculo <|.. Moto
Vehiculo <|.. 4x4
Obstaculo ..> Vehiculo
Vehiculo ..> Pozo
Vehiculo ..> Piquete
Vehiculo ..> ControlPolicial

Moto <.. Grilla
Auto <.. Grilla
4x4 <.. Grilla

Auto --> Posicion
Moto --> Posicion
4x4 --> Posicion





@enduml