@startuml
class Grilla{}

class Vehiculo {
    - movimientos: Integer
    - posicion: Posicion
    + moverse(posicion: Posicion)
    + getPosicionSiguiente(unaDireccion: char)
    + accept(visitor: IVisitor)
    + abrirSopresa(sorpresa: Sorpresa)
    + pasarPor(visitor: IVisitor)
    + recibirSorpresa(cambioVehiculo: CambioVehiculo)
}
interface Ivisitor {
    + visit(auto: Auto)
    + visit(auto4x4: Auto4x4)
    + visit(moto: Moto)
}

interface Tipo {
    + accept(visitor: IVisitor)
}

class Moto {
    + accept(visitor: IVisitor)
}

class Auto {
    + accept(visitor: IVisitor)
}

class Auto4x4 {
    + accept(visitor: IVisitor)
}

class Piquete {
    + visit(auto: Auto)
    + visit(auto4x4: Auto4x4)
    + visit(moto: Moto)
}

class ControlPolicial {
    + visit(auto: Auto)
    + visit(auto4x4: Auto4x4)
    + visit(moto: Moto)
}

class Pozo {
    + visit(auto: Auto)
    + visit(auto4x4: Auto4x4)
    + visit(moto: Moto)
}

Grilla --> Vehiculo
Grilla ..> Ivisitor
Vehiculo --> Tipo
Tipo <|.. Moto
Tipo <|.. Auto
Tipo <|.. Auto4x4
Ivisitor <|.. Piquete
Ivisitor <|.. ControlPolicial
Ivisitor <|.. Pozo

@enduml